### ISSUE TITLE
Remove eslint-plugin-standard from README

### ISSUE THREAD

**Issue by nikolay-borzov** [npetruzzelli/eslint-config-prettier-standard#11]
`standard` 16.0.0 made `eslint-plugin-standard` obsolete
```
npm WARN deprecated eslint-plugin-standard@5.0.0: standard 16.0.0 and eslint-config-standard 16.0.0 no longer require the eslint-plugin-standard package. You can remove it from your dependencies with 'npm rm eslint-plugin-standard'. More info here: https://github.com/standard/standard/issues/1316
```

**Comment by npetruzzelli** [comment]
Thank you for reminding me about this: https://github.com/standard/standard/issues/1316

While **eslint-config-prettier-standard** does not directly consume **eslint-plugin-standard**, some versions of **eslint-config-standard** covered by the current peer dependency range does, so changing the instructions in this way is something that I will treat as a breaking change.

I will proceed as follows:

1.  for `eslint-config-prettier-standard#3.x.x`, I will change the peer dependency to be a range that will prevent the warning
    -   Current: `"eslint-config-standard": ">=12.0.0"`
    -   New: `"eslint-config-standard": ">=12.0.0 - <16.0.0"`
2. I will release a new major version (`4.x.x`) that changes the minimum version and updates the README
    -   New: `"eslint-config-standard": ">=16.0.0"`
